EveryWorkflowSalesOrderBundle:
    resource: '@EveryWorkflowSalesOrderBundle/Resources/config/routes.yaml'

# EveryWorkflowEcommerceBundle_Controller:
#     resource: "../../Controller/"
#     type: annotation
